### ISSUE TITLE
Doesn't work after install, no 'format code' option in right click menu, the shortcut also not work

### ISSUE THREAD

**Issue by Teckee** [win7killer/vue-format#20]

**Comment by win7killer** [comment]
@Teckee  please provide some info.

---
name: Bug report
about: Create a report to help us improve

---

**Describe the bug** [描述]
A clear and concise description of what the bug is.

**To Reproduce**[复现]
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**[预期]
A clear and concise description of what you expected to happen.

**Screenshots**[截图]
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**[环境]
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**[补充]
Add any other context about the problem here.
